
title: code + electronics
email: casey.anderson@artcenter.edu
description:
  This series of interactive workshops introduces students
  to the creative affordances of programming, electronics, their
  interaction, and their potential for controlling media.
  Special emphasis is placed on FOSS technologies that are general purpose and hackable.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://making.caseyanderson.com/"
github_username: caseyanderson

header_pages:
  - about.markdown
  - intro.markdown
  - esp32.markdown
  - rpi.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
